/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaJNITest */

#ifndef _Included_javaJNITest
#define _Included_javaJNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaJNITest
 * Method:    printMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaJNITest_printMethod
  (JNIEnv *, jobject);

/*
 * Class:     javaJNITest
 * Method:    trueFalse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_javaJNITest_trueFalse
  (JNIEnv *, jobject);

/*
 * Class:     javaJNITest
 * Method:    power
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_javaJNITest_power
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     javaJNITest
 * Method:    returnAByteArray
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_javaJNITest_returnAByteArray
  (JNIEnv *, jobject);

/*
 * Class:     javaJNITest
 * Method:    stringManipulator
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_javaJNITest_stringManipulator
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     javaJNITest
 * Method:    heapAlloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javaJNITest_heapAlloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javaJNITest
 * Method:    mmapHooking
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javaJNITest_mmapHooking
  (JNIEnv *, jobject, jlong, jstring);


#ifdef __cplusplus
}
#endif
#endif
